
on: 
    pull_request:
      types: [closed]


concurrency: 
    group: pr-destroy-${{ github.event.pull_request.number }}
    cancel-in-progress: false
    
jobs:
  destroy-pr-stack:
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.get-url.outputs.url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Setup Node.js
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
    - name: Destroy
      run: npm run destroy:force
      env:
        SUFFIX: -pr${{ github.event.pull_request.number }}
